spring:
#  #option if use liquibase
#  liquibase:
#    change-log: classpath:db/changelog/changelog-master.xml
#    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/db_example'
    username: root
    password: root

# H2 option
#    driverClassName: org.h2.Driver
#      url: jdbc:h2:mem:shedlock_DB;INIT=CREATE SCHEMA IF NOT EXISTS shedlock;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:

